# Generated by Django 4.2.13 on 2024-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(5, 'Owner'), (4, 'Manager'), (3, 'Asst Manager'), (2, 'Team Leader'), (1, 'Worker'), (0, 'None')], default=0),
        ),
    ]
