# Generated by Django 4.2.13 on 2024-11-30 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_egg_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_alive_birds', models.PositiveIntegerField(default=0)),
                ('number_of_dead_birds', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('flock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='poultry.flock')),
            ],
            options={
                'verbose_name_plural': 'Flock Inventories',
            },
        ),
        migrations.CreateModel(
            name='FlockInventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_birds', models.PositiveIntegerField()),
                ('mortality_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flock_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='poultry_inventory.flockinventory')),
            ],
            options={
                'verbose_name_plural': 'Flock Inventory Histories',
            },
        ),
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_intake', models.FloatField()),
                ('water_intake', models.FloatField()),
                ('vaccine_administered', models.CharField(max_length=100)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('CustomUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EggInventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('egg_count', models.PositiveIntegerField()),
                ('egg_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_inventory.egginventory')),
            ],
        ),
    ]
