# Generated by Django 4.2.13 on 2024-12-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
        ('poultry_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdata',
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='farmdata',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_data', to='users.organization'),
        ),
    ]
