# Generated by Django 5.0.2 on 2024-10-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_intake', models.FloatField()),
                ('water_intake', models.FloatField()),
                ('vaccine_administered', models.CharField(max_length=100)),
                ('date_recorded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
