# Generated by Django 5.0.2 on 2024-11-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flockbreedinformation',
            name='average_egg_production',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
