# Generated by Django 4.2.13 on 2025-01-28 04:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
        ('poultry', '0002_eggcollection_organization_flock_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='initial_weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flock',
            name='unit_prices',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flockinspectionrecord',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flockinspectionrecord',
            name='date_of_inspection',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('Medication', 'Medication'), ('Vaccination', 'Vaccination'), ('Supplements', 'Supplements')], max_length=20)),
                ('details', models.CharField(max_length=250)),
                ('dosage', models.CharField(max_length=250)),
                ('associated_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('treatment_method', models.CharField(choices=[('Intramuscular', 'Intramuscular'), ('Oral', 'Oral'), ('Subcutaneous', 'Subcutaneous'), ('Topical', 'Topical'), ('Others', 'Others')], max_length=20)),
                ('birds_treated', models.PositiveIntegerField()),
                ('veterinarian', models.CharField(max_length=250)),
                ('notes', models.TextField(null=True)),
                ('date_administered', models.DateField()),
                ('time_administered', models.TimeField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='poultry.flock')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FlockWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5)])),
                ('date_weighed', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='poultry.flock')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Expense', 'Expense'), ('Revenue', 'Revenue')], max_length=10)),
                ('finance_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_occurred', models.DateField()),
                ('beneficiary', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('variety', models.CharField(max_length=250)),
                ('form', models.CharField(choices=[('Crumb/Pellet', 'Crumb'), ('Mash', 'Mash')], max_length=20)),
                ('chicken_type', models.CharField(choices=[('Broilers', 'Broiler'), ('Layers', 'Layers'), ('Multi-Purpose', 'Multi Purpose')], max_length=15)),
                ('growth_stage', models.CharField(choices=[('Starter', 'Starter'), ('Growers', 'Growers'), ('Finisher', 'Finisher'), ('Early Laying', 'Earlylaying'), ('Main Laying', 'Mainlaying')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('size_of_bags', models.PositiveIntegerField()),
                ('purchase_date', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_weight', models.FloatField()),
                ('water_qty', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('feed_date', models.DateField()),
                ('feed_time', models.TimeField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding', to='poultry.feedpurchase')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding', to='poultry.flock')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EggSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_crates', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_sold', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egg_sales', to='users.organization')),
            ],
        ),
    ]
