# Generated by Django 4.2.13 on 2025-02-02 20:54

from django.db import migrations, models
import django.utils.timezone
import poultry.models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_flock_initial_weight_flock_unit_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flock',
            name='date_of_hatching',
        ),
        migrations.AddField(
            model_name='finance',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flock',
            name='age_in_weeks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eggsales',
            name='date_sold',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_time',
            field=models.TimeField(default=poultry.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='finance',
            name='date_occurred',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flock',
            name='date_established',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flockweight',
            name='date_weighed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date_administered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='time_administered',
            field=models.TimeField(default=poultry.models.get_current_time),
        ),
    ]
