# Generated by Django 4.2.13 on 2025-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_remove_flock_date_of_hatching_finance_date_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='total_bags',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
